project_name: nr-dashboard-hcl-gen
before:
  hooks:
    - go mod download
builds:
  - id: nr-dashboard-hcl-gen
    dir: ./cmd
    binary: nr-dashboard-hcl-gen
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
